name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s
 run: sudo apt-get update && sudo apt-get upgrade -y
 run: sudo apt-get install python3-pip ffmpeg -y
run: sudo pip3 install -U pip
run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && source ~/.bashrc && nvm install v18
 run: pip3 install -U -r requirements.txt
 run: cp sample.env .env
run: sudo apt install tmux -y && tmux
 run: bash start
