name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

jobs:
build:
run-on:ubuntu-latest
steps:
 - uses: actions/checkout@v4
 - name: Running
 run: pip install pyrogram
 run: pip install dotenv
 run: tmrx
run: termux
 run: bash start
